[tool.black]
line-length = 100
target-version = ["py310"]
 
[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
select = ["T100"]
ignore = ["F722"]

[tool.mypy]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
no_implicit_reexport = true
python_version = "3.10"
strict_concatenate = true
strict_equality = true
warn_redundant_casts = true
warn_unused_configs = true
